-- Generation AI tools-app — Seed Content V1
-- Im Supabase SQL Editor ausführen (nach schema.sql)

INSERT INTO content_items (type, status, title, slug, summary, content, category, tags, use_cases, pricing_model, external_url, logo_domain, quick_win) VALUES

('tool', 'published', 'ChatGPT', 'chatgpt',
 'Der KI-Chatbot von OpenAI. Einstieg in generative KI für die meisten — vielseitig, einfach, kostenlos nutzbar.',
 E'## Was ist ChatGPT?\nChatGPT ist der bekannteste KI-Assistent und für die meisten der erste Berührungspunkt mit generativer KI. Entwickelt von OpenAI, läuft auf GPT-4o.\n\n## Was kann er besonders gut?\n- Texte schreiben, überarbeiten, kürzen\n- Themen erklären und vereinfachen\n- Brainstorming und Ideenentwicklung\n- Code erklären und debuggen\n- Zusammenfassungen aus langen Texten\n\n## So nutzt du es als Studierender\nNutze ChatGPT als ersten Ansprechpartner für alles: Textentwürfe, Erklärungen, Prüfungsvorbereitung. Starte immer mit Kontext: wer du bist, was du brauchst, für wen es ist.\n\n## Pricing\nKostenlos mit GPT-4o mini. Plus (20 USD/Monat) bringt GPT-5, Canvas, Projects, Bild-Generierung.\n\n## Quick Win\nFrag: "Erklär mir [Thema] wie einem 12-Jährigen" — schnellster Weg um schwierige Konzepte zu verstehen.\n\n## Alternativen\n- Claude: besser bei langen Texten und nuanciertem Schreiben\n- Gemini: Google-Integration, gut für Search-Kombination',
 'Schreiben & Chat', ARRAY['chat','schreiben','openai','allrounder'],
 ARRAY['Texte schreiben','Brainstorming','Prüfungsvorbereitung','Code erklären'],
 'freemium', 'https://chat.openai.com', 'openai.com',
 'Gib deiner nächsten Frage Kontext: "Ich bin BWL-Student im 4. Semester und schreibe über X. Erkläre mir Y." — die Antwortqualität verdoppelt sich.'),

('tool', 'published', 'Claude', 'claude',
 'Der KI-Assistent von Anthropic. Stärker als ChatGPT bei langen Texten, Nuancen und ehrlichem, reflektiertem Ton.',
 E'## Was ist Claude?\nClaude von Anthropic ist Chatbot und Thinking Partner. Besonders stark bei sehr langen Kontexten (bis 200.000 Tokens — ganze PDFs am Stück), präzisem Schreiben und ehrlicher Selbsteinschätzung.\n\n## Was kann er besonders gut?\n- Lange PDFs, Papers und Dokumente analysieren\n- Nuancierte Argumentationen schreiben und hinterfragen\n- Code reviewen und erklären\n- Als Sparringspartner für komplexe Themen\n- Eigene Einschätzung geben statt nur zu bestätigen\n\n## So nutzt du es als Studierender\nLad dein Thesis-Kapitel oder Paper als PDF hoch. Frag gezielt: "Was ist die schwächste Stelle in meiner Argumentation?" oder "Welche Gegenargumente habe ich nicht berücksichtigt?"\n\n## Pricing\nKostenlos (Claude Sonnet). Pro (20 USD/Monat) für unlimitierten Zugang, Projects und höhere Kontextlänge.\n\n## Quick Win\nLad ein Paper hoch und frag: "Fass die Kernaussage in 3 Sätzen zusammen und erkläre welche Methodik genutzt wurde."\n\n## Alternativen\n- ChatGPT: breiter bekannt, mehr Plugins\n- Gemini: besser für Google-Docs-Integration',
 'Schreiben & Chat', ARRAY['chat','long-context','anthropic','pdf','schreiben'],
 ARRAY['Thesis schreiben','Papers analysieren','Argumentationen prüfen','Texte überarbeiten'],
 'freemium', 'https://claude.ai', 'anthropic.com',
 'Lad dein Thesis-Kapitel als PDF hoch und frag: "Was ist die schwächste Stelle in meiner Argumentation?" — bekommst konkrete, ehrliche Kritik.'),

('tool', 'published', 'Perplexity', 'perplexity',
 'KI-Suchmaschine mit Quellen. Direkte Antworten statt SEO-Müll — perfekt für schnelle, belegbare Recherche.',
 E'## Was ist Perplexity?\nPerplexity kombiniert Websuche mit LLMs und zitiert jede Aussage direkt mit Quellen. Ersatz für Google bei inhaltlichen Fragen: du bekommst eine Antwort statt 10 Links.\n\n## Was kann es besonders gut?\n- Aktuelle Informationen mit Quellenangaben\n- Schnelle Faktenrecherche ohne Quellen-Kuration\n- Themen-Übersichten mit verlinkten Primärquellen\n- Vergleiche zwischen Konzepten oder Produkten\n- Pro Search für tiefere Recherche-Läufe\n\n## So nutzt du es als Studierender\nNutze Perplexity für den ersten Recherche-Schritt: Überblick verschaffen, Schlüsselquellen finden, Definitionen klären. Dann tiefer in die gefundenen Primärquellen gehen.\n\n## Pricing\nKostenlos für Standard-Suche. Pro (20 USD/Monat) bringt Claude/GPT als Backend-Wahl und unbegrenzte Pro-Suchen. Für viele Studis via Hochschul-Kooperationen kostenlos.\n\n## Quick Win\nStell deine Hausarbeits-Frage als vollständigen Satz — die Antwort kommt mit zitierbaren Quellen.\n\n## Alternativen\n- Google Scholar: für akademische Paper direkt\n- ChatGPT mit Search: ähnlich, aber weniger fokussiert auf Quellen',
 'Recherche', ARRAY['suche','recherche','quellen','aktuell'],
 ARRAY['Literaturrecherche','Faktencheck','Themenüberblick','Quellen finden'],
 'freemium', 'https://perplexity.ai', 'perplexity.ai',
 'Stell eine komplette Frage statt Keywords: "Welche Auswirkungen hat Inflation auf Studierende in Deutschland?" — bekommst eine Antwort mit Quellen statt Links.'),

('tool', 'published', 'Cursor', 'cursor',
 'Der KI-Code-Editor. Schreibt ganze Features, erklärt Code, refactort Repositories — wie Pair Programming mit einem sehr schnellen Kollegen.',
 E'## Was ist Cursor?\nCursor ist ein Fork von VS Code mit tief integrierter KI. Composer generiert und refactort über mehrere Dateien gleichzeitig, Tab-Autocomplete ist präziser als Copilot, Chat kennt dein ganzes Repository.\n\n## Was kann er besonders gut?\n- Features über mehrere Dateien gleichzeitig implementieren\n- Bestehenden Code erklären und dokumentieren\n- Bugs mit Kontext aus dem ganzen Codebase debuggen\n- Tests automatisch schreiben\n- Neue Frameworks durch Mitmachen lernen\n\n## So nutzt du es als Studierender\nErstell ein neues Projekt, öffne Cursor, drück Cmd+I (Composer) und beschreibe was du bauen willst. Cursor plant die Umsetzung über alle Dateien.\n\n## Pricing\nHobby kostenlos mit Limits. Pro (20 USD/Monat) für unbegrenzte Nutzung mit Claude und GPT-5.\n\n## Quick Win\nMarkiere einen Code-Block, drück Cmd+K, beschreib die Änderung in einem Satz — Cursor schreibt den Diff direkt.\n\n## Alternativen\n- GitHub Copilot: günstiger, weniger mächtig\n- Windsurf: ähnlich, andere UX\n- Claude: für Code-Fragen ohne Editor-Integration',
 'Coding', ARRAY['code','editor','ide','developer','vs-code'],
 ARRAY['Code schreiben','Features implementieren','Bugs debuggen','Programmieren lernen'],
 'freemium', 'https://cursor.com', 'cursor.com',
 'Drück Cmd+K in einer Datei, beschreib was der Code machen soll — Cursor schreibt direkt in den Editor.'),

('tool', 'published', 'GitHub Copilot', 'github-copilot',
 'KI-Autocomplete direkt im Editor. Für Studierende über das GitHub Student Pack kostenlos.',
 E'## Was ist GitHub Copilot?\nCopilot von GitHub und OpenAI ergänzt deinen Code in Echtzeit — direkt in VS Code, JetBrains, Neovim. Copilot Chat beantwortet Fragen zum Repository.\n\n## Was kann er besonders gut?\n- Boilerplate automatisch vervollständigen\n- Tests aus Code generieren\n- Regex, SQL und komplexe Syntax vorschlagen\n- Unbekannte APIs durch Beispiele lernen\n- Inline-Dokumentation schreiben\n\n## So nutzt du es als Studierender\nBeantrags das GitHub Student Developer Pack mit deiner Uni-Mail-Adresse. Copilot ist eines von über 100 kostenlosen Tools darin.\n\n## Pricing\nFür Studierende kostenlos über GitHub Student Pack. Sonst 10 USD/Monat.\n\n## Quick Win\nBeantrag heute das Student Pack auf education.github.com — Copilot plus viele weitere Tools sofort kostenlos.\n\n## Alternativen\n- Cursor: mächtiger, aber eigenständiger Editor\n- Codeium: kostenlose Alternative ohne Student-Verifikation',
 'Coding', ARRAY['code','autocomplete','github','student'],
 ARRAY['Code schreiben','Tests generieren','Programmieren lernen','Boilerplate'],
 'freemium', 'https://github.com/features/copilot', 'github.com',
 'education.github.com → Student Pack beantragen mit Uni-Mail → Copilot sofort kostenlos.'),

('tool', 'published', 'Notion AI', 'notion-ai',
 'KI direkt in Notion. Fasst Meeting-Notes zusammen, schreibt Entwürfe und beantwortet Fragen zu deinem ganzen Workspace.',
 E'## Was ist Notion AI?\nNotion AI ist in die Notion-App integriert: Schreib-Assistent in jeder Seite, Q&A über den ganzen Workspace, AI Meeting Notes, smarte Zusammenfassungen.\n\n## Was kann es besonders gut?\n- Meeting-Notizen automatisch strukturieren\n- Entwürfe aus Stichpunkten ausformulieren\n- Fragen zum eigenen Workspace beantworten\n- Texte kürzen, übersetzen, umschreiben\n- Datenbanken mit AI-Spalten anreichern\n\n## So nutzt du es als Studierender\nSinnvoll wenn du Notion ohnehin für Notizen nutzt. Leg Vorlesungsnotizen ab, dann frag "Was waren die Kernaussagen dieser Woche?" — antwortet mit Verweisen.\n\n## Pricing\nNotion Free + AI kostet ca. 10 USD/Monat extra. Nur sinnvoll wenn du Notion aktiv nutzt.\n\n## Quick Win\nSammel deine Vorlesungsnotizen in Notion, dann frag AI: "Erstell mir eine Zusammenfassung der wichtigsten Konzepte für die Prüfung."\n\n## Alternativen\n- Obsidian + KI-Plugins: mehr Kontrolle, steiler Einstieg\n- Reflect: KI-first Notiz-App',
 'Produktivität', ARRAY['notion','notizen','workspace','produktivität'],
 ARRAY['Notizen organisieren','Meeting-Protokolle','Prüfungsvorbereitung','Entwürfe schreiben'],
 'paid', 'https://notion.so/product/ai', 'notion.so',
 'Schreib deine Vorlesungsmitschriften als Stichpunkte rein, dann: /AI → "Schreib das als strukturierte Zusammenfassung aus."'),

('tool', 'published', 'Make', 'make',
 'No-Code-Automation-Plattform. Verbindet Apps und APIs visuell — wiederkehrende Aufgaben eliminieren ohne eine Zeile Code.',
 E'## Was ist Make?\nMake (früher Integromat) ist die visuelle Plattform für Workflow-Automatisierung. Drag-and-drop Scenarios verbinden hunderte Apps: Gmail, Notion, Airtable, Slack, WhatsApp, KI-APIs.\n\n## Was kann es besonders gut?\n- Komplexe mehrstufige Workflows ohne Code\n- Daten zwischen Apps automatisch synchronisieren\n- KI-APIs (Claude, OpenAI) in Workflows einbauen\n- Fehler-Handling und Wiederholungen einbauen\n- Günstiger und flexibler als Zapier\n\n## So nutzt du es als Studierender\nErstell einen Account, such einen Template für deinen Use Case (z.B. "New Gmail → Notion Task"), klone ihn und passe ihn an.\n\n## Pricing\nKostenlos: 1.000 Operations/Monat. Core (9 USD/Monat) für 10.000 Ops, mehr Scenario-Komplexität.\n\n## Quick Win\nBau in 10 Minuten: Neue Mail mit bestimmtem Betreff → KI fasst sie zusammen → schickt dir WhatsApp.\n\n## Alternativen\n- Zapier: einfacher, teurer\n- n8n: open source, selbst hosten\n- Pipedream: developer-focused',
 'Automation', ARRAY['automation','no-code','workflow','integration'],
 ARRAY['Aufgaben automatisieren','Apps verbinden','KI in Workflows','Repetition eliminieren'],
 'freemium', 'https://make.com', 'make.com',
 'Geh auf make.com/templates, suche "Gmail Notion" — klone einen Template und du hast in 5 Minuten deinen ersten Automation-Flow.'),

('tool', 'published', 'Gamma', 'gamma',
 'KI-Präsentationen in Minuten. Aus einem Prompt eine komplette Slide-Deck — besser designed als die meisten manuellen PowerPoints.',
 E'## Was ist Gamma?\nGamma generiert Präsentationen, Dokumente und Websites aus Text-Prompts. Professionelle Templates, responsive Layouts, automatische Bilder — fertig in Minuten statt Stunden.\n\n## Was kann es besonders gut?\n- Vollständige Präsentationen aus einem Satz generieren\n- Eigene Inhalte in schöne Slides umwandeln\n- Präsentationen ohne Design-Kenntnisse\n- Export als PDF und PPTX\n- Interaktive Elemente und Animationen\n\n## So nutzt du es als Studierender\nGib dein Thema oder dein Abstract ein, wähle Anzahl Slides und Stil — Gamma generiert einen vollständigen Entwurf den du nur noch anpassen musst.\n\n## Pricing\nKostenlos mit Watermark (400 KI-Credits). Plus (10 USD/Monat) für unlimitierte Generierung ohne Watermark.\n\n## Quick Win\nKopier dein Thesis-Abstract in Gamma → "Erstell eine 10-Slide-Präsentation" → Entwurf steht in 60 Sekunden, dann nur noch anpassen.\n\n## Alternativen\n- Beautiful.ai: ähnlich, teurer\n- Canva AI: mehr Design-Optionen, weniger AI-Automation\n- Tome: ähnliches Konzept',
 'Präsentationen', ARRAY['präsentation','slides','design','no-code','ki-generierung'],
 ARRAY['Seminarvorträge','Pitch-Decks','Projektvorstellungen','Schnelle Präsentationen'],
 'freemium', 'https://gamma.app', 'gamma.app',
 'Abstract oder Gliederung reinkopieren → "+ New with AI" → Slide-Deck steht in unter einer Minute.'),

('tool', 'published', 'Midjourney', 'midjourney',
 'Der Goldstandard für KI-Bildgenerierung. Bessere Ästhetik und Stil-Konsistenz als fast alle Alternativen.',
 E'## Was ist Midjourney?\nMidjourney ist der führende Dienst für KI-Bildgenerierung. Texteingabe → professionelle Bilder in Sekunden. Besonders stark bei ästhetischer Konsistenz und künstlerischen Stilen.\n\n## Was kann es besonders gut?\n- Fotorealistische Bilder aus Beschreibungen\n- Konsistente Ästhetik über mehrere Bilder\n- Vielfältige Stile: realistisch, illustrativ, abstrakt\n- Variantengenerierung und Upscaling\n- Gut für Moodboards und Konzept-Visuals\n\n## So nutzt du es als Studierender\nNutze Midjourney für Präsentations-Visuals, Moodboards und kreative Projekte. Beschreib das Bild auf Englisch mit Stil-Angaben.\n\n## Pricing\nKein Free-Tier. Basic ab 10 USD/Monat (200 Bilder). Standard 30 USD/Monat unbegrenzt.\n\n## Quick Win\nFüg "--ar 16:9 --style raw" an deinen Prompt an — gibt Folien-kompatible Bilder ohne den typischen KI-Look.\n\n## Alternativen\n- FLUX (kostenlos via Hugging Face): sehr gut, kostenlos\n- Leonardo.ai: freemium, ähnliche Qualität\n- Adobe Firefly: in Creative Cloud integriert',
 'Bilder & Design', ARRAY['bilder','design','generierung','kreativ','visuell'],
 ARRAY['Präsentations-Visuals','Moodboards','Marketing-Material','Kreativprojekte'],
 'paid', 'https://midjourney.com', 'midjourney.com',
 'Beschreib dein Bild auf Englisch und häng "--ar 16:9 --style raw" dran — für saubere, nicht-kitschige Präsentationsbilder.'),

('tool', 'published', 'Whisper', 'whisper',
 'Open-Source Speech-to-Text von OpenAI. Transkribiert Vorlesungen, Interviews und Meetings in über 90 Sprachen — erstaunlich präzise.',
 E'## Was ist Whisper?\nWhisper ist OpenAIs Open-Source ASR-Modell. Es transkribiert Sprache in Text mit sehr hoher Genauigkeit — auch bei Deutsch, Dialekten und gemischten Sprachen.\n\n## Was kann es besonders gut?\n- Automatische Spracherkennung in 90+ Sprachen\n- Sehr gut bei Deutsch und Code-Switching\n- Läuft lokal auf dem Mac (M-Chip) — komplett privat\n- Transkription mit Zeitstempeln\n- Günstig über API (0,006 USD/Minute)\n\n## So nutzt du es als Studierender\nNimm Vorlesungen mit dem Handy auf. Jag die Datei danach durch eine Whisper-App. Das Transcript ist in Minuten fertig und durchsuchbar.\n\n## Pricing\nOpen Source (kostenlos selbst betreiben). API: 0,006 USD/Minute. MacWhisper: einmalig 15 USD für die beste Mac-App.\n\n## Quick Win\nLad MacWhisper (macwhisper.goodsnooze.com) runter — Audiodatei reinziehen → Transcript mit Zeitstempeln in 2 Minuten.\n\n## Alternativen\n- Otter.ai: freemium, live Transkription\n- Fireflies.ai: Meeting-fokussiert\n- AssemblyAI: API-basiert, mehr Features',
 'Audio & Transkription', ARRAY['audio','transkription','speech-to-text','open-source','vorlesungen'],
 ARRAY['Vorlesungen transkribieren','Interviews auswerten','Meeting-Protokolle','Podcast-Transkription'],
 'open_source', 'https://openai.com/research/whisper', 'openai.com',
 'Handy-Aufnahme der Vorlesung + MacWhisper = durchsuchbares Transcript in 2 Minuten. Nie wieder Mitschriften abtippen.');
